### ISSUE TITLE
Question on dot product nodes

### ISSUE THREAD

**Issue by fengqi0423** [zgw21cn/DeepFM#2]
`second_order = np.zeros([sample_size,1])`

`second_order = second_order+tf.reshape(tf.reduce_sum(tf.multiply(former, later), 1, keep_dims=True ),[sample_size,1])`

It seems all the second order product are added together before sending to the output layer.

However, in the paper each dot product node are connected to the output. How should we understand this piece of code?

**Comment by lovetimil** [comment]
rote.

**Comment by fengqi0423** [comment]
nvm the paper said those are weight-1 connections
